//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkControlEntities : DbContext
    {
        public WorkControlEntities()
            : base("name=WorkControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<ProgramTime> ProgramTime { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TimeProfiles> TimeProfiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkWeeks> WorkWeeks { get; set; }
    }
}
