//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramTime
    {
        public int ProgramTimeId { get; set; }
        public int ProgramId { get; set; }
        public int StatsId { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Stats Stats { get; set; }
    }
}
