//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkWeeks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkWeeks()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int WorkWeekId { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> Sunday { get; set; }
        public string NameOfWeek { get; set; }
    
        public virtual TimeProfiles TimeProfiles { get; set; }
        public virtual TimeProfiles TimeProfiles1 { get; set; }
        public virtual TimeProfiles TimeProfiles2 { get; set; }
        public virtual TimeProfiles TimeProfiles3 { get; set; }
        public virtual TimeProfiles TimeProfiles4 { get; set; }
        public virtual TimeProfiles TimeProfiles5 { get; set; }
        public virtual TimeProfiles TimeProfiles6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
